version: '3'

services:

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: __2018bb
      POSTGRES_DB: wallnut-studios
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5434:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
